name: CI

on:
  push:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Install hdf5
      run: |
        sudo apt-get update && sudo apt-get install libhdf5-openmpi-dev 
    - uses: actions/checkout@master
    - name: Configure
      run: |
          mkdir build && cd build && cmake ..
      env:
        BOOST_ROOT: ${BOOST_ROOT_1_72_0}
        BOOST_INCLUDEDIR: "${BOOST_ROOT_1_72_0}/boost/include"
        BOOST_LIBRARYDIR: "${BOOST_ROOT_1_72_0}\lib"
    - name: Build
      working-directory: build
      run: |
          make
    - name: Test
      working-directory: build
      run: |
          make test
